borre import
LeandroCadena/Esthetic-App pull request #44
Opened 2021-07-11 20:43 UTC by eugebutta

2021-07-11 21:02 UTC, gabrieldegiorgi submitted a review, later dismissed

2021-07-12 13:10 UTC, Dabuaf86 commented on client/src/components/UserRegister/UserRegister.js
> +  const cellphone = useInput("cellphone");
Hay que cambiar cellphone por phone, Euge.

2021-07-12 13:10 UTC, Dabuaf86 requested changes
Recordar cambiar el campo de "cellphone" por "phone".

2021-07-12 13:13 UTC, eugebutta commented on client/src/components/UserRegister/UserRegister.js
> +  const cellphone = useInput("cellphone");
oka

2021-07-12 13:14 UTC, Dabuaf86 approved these changes

2021-07-12 13:16 UTC, merged